// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwhjuggrdxmdmdkcolkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3aGp1Z2dyZHhtZG1ka2NvbGtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTA3MTgsImV4cCI6MjA2NTQ2NjcxOH0.Kdesc54s-OiKzpbZev3vTHRTMaTq8c1_oznJwigCMsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);